[2025-06-05 02:21:12] [-] No relevant document found for index 1: Fritz Cos Inc & United Parcel Service Inc
[2025-06-05 02:21:21] [+] Successfully created document for: Allaire Corp & Macromedia Inc
[2025-06-05 02:21:24] [+] Successfully created document for: Mediconsult.com Inc & CyBear Inc(Andryx Corp)
[2025-06-05 02:21:25] [+] Successfully created document for: Prime Response Inc & Chordiant Software Inc
[2025-06-05 02:21:26] [+] Successfully created document for: Xircom Inc & Intel Corp
[2025-06-05 02:21:56] [+] Successfully created document for: Texoil Inc & Ocean Energy Inc
[2025-06-05 02:22:00] [+] Successfully created document for: WebTrends Corp & NetIQ Corp
[2025-06-05 02:22:00] [+] Successfully created document for: Centennial Technologies Inc & Solectron Corp
[2025-06-05 02:22:01] [+] Successfully created document for: Pontotoc Production Inc & Ascent Energy Inc
[2025-06-05 02:22:04] [+] Successfully created document for: Guest Supply Inc & Sysco Corp
[2025-06-05 02:22:36] [+] Successfully created document for: Heartport Inc & Johnson & Johnson
[2025-06-05 02:22:36] [+] Successfully created document for: Dallas-Semiconductor Corp & Maxim Integrated Products Inc
[2025-06-05 02:22:37] [+] Successfully created document for: Tosco Corp & Phillips Petroleum Co Inc
[2025-06-05 02:22:39] [+] Successfully created document for: Sensory Science Corp & SONICBlue Inc
[2025-06-05 02:22:45] [+] Successfully created document for: Credit Management Solutions & First American Corp
[2025-06-05 02:23:14] [+] Successfully created document for: UTI Energy Corp & Patterson Energy Inc
[2025-06-05 02:23:26] [+] Successfully created document for: Women.com Networks & iVillage Inc
[2025-06-05 02:23:29] [+] Successfully created document for: New Era of Networks Inc & Sybase Inc
[2025-06-05 02:23:33] [+] Successfully created document for: Conectiv Inc & Potomac Electric Power Company
[2025-06-05 02:23:42] [*] No background section found for index 19: RGS Energy Group & Energy East Corp. Retrying via fallback...
[2025-06-05 02:23:42] [-] Confirmed no background section found for index 19: RGS Energy Group & Energy East Corp.
	Dumping its document links:
		https://www.sec.gov/Archives/edgar/data/1073353/000091205701007680/0000912057-01-007680.txt
		https://www.sec.gov/Archives/edgar/data/1046861/000091205701509743/0000912057-01-509743.txt
[2025-06-05 02:24:10] [+] Successfully created document for: Fourth Shift Corp & AremisSoft Corp
[2025-06-05 02:24:18] [+] Successfully created document for: ASI Solutions Inc & Aon Corp
[2025-06-05 02:24:18] [+] Successfully created document for: Oshman's Sporting Goods Inc & Gart Sports Co
[2025-06-05 02:24:37] [*] No background section found for index 20: Blue Wave Systems Inc & Motorola Inc. Retrying via fallback...
[2025-06-05 02:24:37] [-] Confirmed no background section found for index 20: Blue Wave Systems Inc & Motorola Inc.
	Dumping its document links:
		https://www.sec.gov/Archives/edgar/data/68505/000091205701516258/0000912057-01-516258.txt
		https://www.sec.gov/Archives/edgar/data/68505/000091205701518301/0000912057-01-518301.txt
[2025-06-05 02:24:50] [+] Successfully created document for: Spieker Properties Inc & Equity Office Properties Trust
[2025-06-05 02:25:41] [-] No relevant document found for index 27: United Dominion Industries Ltd & SPX Corp
[2025-06-05 02:25:51] [+] Successfully created document for: Towne Services Inc & Private Business Inc
[2025-06-05 02:25:53] [+] Successfully created document for: Cambridge Technology Partners & Novell Inc
[2025-06-05 02:25:54] [+] Successfully created document for: Data Dimensions Inc & Lionbridge Technologies Inc
[2025-06-05 02:25:56] [+] Successfully created document for: VitalCom Inc & Data Critical Corp
[2025-06-05 02:26:11] [-] No relevant document found for index 31: True North Communications Inc & Interpublic Group of Cos Inc
[2025-06-05 02:26:23] [+] Successfully created document for: Sequoia Software Corp & Citrix Systems Inc
[2025-06-05 02:26:24] [+] Successfully created document for: Huntway Refining Co & Valero Energy Corp
[2025-06-05 02:26:28] [+] Successfully created document for: CUseeMe Networks Inc & First Virtual Communications
[2025-06-05 02:26:38] [+] Successfully created document for: Bergen Brunswig Corp & AmeriSource Health Corp
[2025-06-05 02:26:57] [-] No relevant document found for index 39: General Semiconductor Inc & Vishay Intertechnology Inc
[2025-06-05 02:27:11] [+] Successfully created document for: Interland Inc & Micron Electronics Inc
[2025-06-05 02:27:12] [+] Successfully created document for: ALZA Corp & Johnson & Johnson
[2025-06-05 02:27:14] [+] Successfully created document for: Franchise Finance Corp of Amer & General Electric Capital Corp
[2025-06-05 02:27:14] [+] Successfully created document for: Kent Electronics Corp & Avnet Inc
[2025-06-05 02:27:43] [+] Successfully created document for: Dean Foods Co & Suiza Foods Corp
[2025-06-05 02:27:44] [+] Successfully created document for: Exigent International Inc & Harris Corp
[2025-06-05 02:27:47] [+] Successfully created document for: Broadbase Software Inc & Kana Communications Inc
[2025-06-05 02:27:52] [+] Successfully created document for: DTM Corp & 3D Systems Corp
[2025-06-05 02:27:54] [+] Successfully created document for: USA Detergents Inc & Church & Dwight Co Inc
[2025-06-05 02:28:13] [-] No relevant document found for index 45: Ravenswood Winery Inc & Constellation Brands Inc
[2025-06-05 02:28:14] [-] No relevant document found for index 49: Allergan Specialty & Allergan Inc
[2025-06-05 02:28:26] [+] Successfully created document for: Foilmark Inc & Illinois Tool Works Inc
[2025-06-05 02:28:28] [+] Successfully created document for: McNaughton Apparel Group Inc & Jones Apparel Group Inc
[2025-06-05 02:28:34] [+] Successfully created document for: Autoweb.com Inc & Autobytel.com Inc
[2025-06-06 01:31:32] [+] Successfully created document for: Blue Wave Systems Inc & Motorola Inc
[2025-06-06 01:33:42] [+] Successfully created document for: RGS Energy Group & Energy East Corp
[2025-06-06 01:38:17] [+] Successfully created document for: RGS Energy Group & Energy East Corp
[2025-06-06 02:29:35] [-] Process failed with error: Traceback (most recent call last):
  File "D:\Documents\Scripts\MergeExtractor\src\seperator\SeperatorHandler.py", line 157, in runSeperator
    future.result();
    ^^^^^^^^^^^^^^^
  File "C:\Users\bryan\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bryan\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

[2025-06-06 02:29:35] [-] Process failed with error: Traceback (most recent call last):
  File "D:\Documents\Scripts\MergeExtractor\src\seperator\SeperatorHandler.py", line 157, in runSeperator
    future.result();
    ^^^^^^^^^^^^^^^
  File "C:\Users\bryan\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bryan\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "D:\Documents\Scripts\MergeExtractor\src\seperator\SeperatorHandler.py", line 157, in runSeperator
    future.result();
    ^^^^^^^^^^^^^^^
  File "C:\Users\bryan\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bryan\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

[2025-06-06 02:29:35] [-] Process failed with error: Traceback (most recent call last):
  File "D:\Documents\Scripts\MergeExtractor\src\seperator\SeperatorHandler.py", line 157, in runSeperator
    future.result();
    ^^^^^^^^^^^^^^^
  File "C:\Users\bryan\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bryan\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "D:\Documents\Scripts\MergeExtractor\src\seperator\SeperatorHandler.py", line 157, in runSeperator
    future.result();
    ^^^^^^^^^^^^^^^
  File "C:\Users\bryan\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bryan\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "D:\Documents\Scripts\MergeExtractor\src\seperator\SeperatorHandler.py", line 157, in runSeperator
    future.result();
    ^^^^^^^^^^^^^^^
  File "C:\Users\bryan\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bryan\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

[2025-06-06 18:19:08] [-] Error: cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "D:\Documents\Scripts\MergeExtractor\src\seperator\SeperatorHandler.py", line 66, in process_single_doc
    chunks, approx_chunks = chunk_processor.locateBackgroundChunk(text, START_PHRASES, executor);
    ^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object

[2025-06-06 18:22:08] [-] Error processing https://www.sec.gov/Archives/edgar/data/1042134/000101287001000359/0001012870-01-000359.txt: cannot access local variable 'result' where it is not associated with a value
[2025-06-06 18:22:12] [-] Error processing https://www.sec.gov/Archives/edgar/data/1042134/000101287001000987/0001012870-01-000987.txt: cannot access local variable 'result' where it is not associated with a value
[2025-06-06 18:22:12] [*] No background section found for index 0: Prime Response Inc & Chordiant Software Inc. Retrying via fallback...
[2025-06-06 18:22:12] [-] Confirmed no background section found for index 0: Prime Response Inc & Chordiant Software Inc.
	Dumping its document links:
		https://www.sec.gov/Archives/edgar/data/1042134/000101287001000987/0001012870-01-000987.txt
		https://www.sec.gov/Archives/edgar/data/1042134/000101287001000359/0001012870-01-000359.txt
[2025-06-06 18:23:14] [-] Error processing https://www.sec.gov/Archives/edgar/data/1042134/000101287001000987/0001012870-01-000987.txt: Error in process_document; ChunkProcessor.locateBackgroundChunk returning None is unexpected FATAL! No chunks with dates found.
[2025-06-06 18:23:14] [-] Error processing https://www.sec.gov/Archives/edgar/data/1042134/000101287001000359/0001012870-01-000359.txt: Error in process_document; ChunkProcessor.locateBackgroundChunk returning None is unexpected FATAL! No chunks with dates found.
[2025-06-06 18:23:14] [*] No background section found for index 0: Prime Response Inc & Chordiant Software Inc. Retrying via fallback...
[2025-06-06 18:23:14] [-] Confirmed no background section found for index 0: Prime Response Inc & Chordiant Software Inc.
	Dumping its document links:
		https://www.sec.gov/Archives/edgar/data/1042134/000101287001000359/0001012870-01-000359.txt
		https://www.sec.gov/Archives/edgar/data/1042134/000101287001000987/0001012870-01-000987.txt
[2025-06-06 18:30:19] [-] Error processing https://www.sec.gov/Archives/edgar/data/1042134/000101287001000987/0001012870-01-000987.txt: cannot access local variable 'result' where it is not associated with a value
[2025-06-06 18:30:23] [-] Error processing https://www.sec.gov/Archives/edgar/data/1042134/000101287001000359/0001012870-01-000359.txt: cannot access local variable 'result' where it is not associated with a value
[2025-06-06 18:30:23] [*] No background section found for index 0: Prime Response Inc & Chordiant Software Inc. Retrying via fallback...
[2025-06-06 18:30:23] [-] Confirmed no background section found for index 0: Prime Response Inc & Chordiant Software Inc.
	Dumping its document links:
		https://www.sec.gov/Archives/edgar/data/1042134/000101287001000359/0001012870-01-000359.txt
		https://www.sec.gov/Archives/edgar/data/1042134/000101287001000987/0001012870-01-000987.txt
[2025-06-06 18:31:54] [-] Error processing https://www.sec.gov/Archives/edgar/data/1042134/000101287001000359/0001012870-01-000359.txt: cannot access local variable 'result' where it is not associated with a value
[2025-06-06 18:31:58] [-] Error processing https://www.sec.gov/Archives/edgar/data/1042134/000101287001000987/0001012870-01-000987.txt: cannot access local variable 'result' where it is not associated with a value
[2025-06-06 18:31:58] [*] No background section found for index 0: Prime Response Inc & Chordiant Software Inc. Retrying via fallback...
[2025-06-06 18:31:58] [-] Confirmed no background section found for index 0: Prime Response Inc & Chordiant Software Inc.
	Dumping its document links:
		https://www.sec.gov/Archives/edgar/data/1042134/000101287001000359/0001012870-01-000359.txt
		https://www.sec.gov/Archives/edgar/data/1042134/000101287001000987/0001012870-01-000987.txt
[2025-06-06 18:33:47] [-] Error processing https://www.sec.gov/Archives/edgar/data/1042134/000101287001000987/0001012870-01-000987.txt: cannot access local variable 'result' where it is not associated with a value
[2025-06-06 18:33:51] [-] Error processing https://www.sec.gov/Archives/edgar/data/1042134/000101287001000359/0001012870-01-000359.txt: cannot access local variable 'result' where it is not associated with a value
[2025-06-06 18:33:51] [*] No background section found for index 0: Prime Response Inc & Chordiant Software Inc. Retrying via fallback...
[2025-06-06 18:33:51] [-] Confirmed no background section found for index 0: Prime Response Inc & Chordiant Software Inc.
	Dumping its document links:
		https://www.sec.gov/Archives/edgar/data/1042134/000101287001000359/0001012870-01-000359.txt
		https://www.sec.gov/Archives/edgar/data/1042134/000101287001000987/0001012870-01-000987.txt
[2025-06-06 18:36:34] [-] Error processing https://www.sec.gov/Archives/edgar/data/1042134/000101287001000987/0001012870-01-000987.txt: cannot access local variable 'result' where it is not associated with a value
[2025-06-06 18:36:38] [-] Error processing https://www.sec.gov/Archives/edgar/data/1042134/000101287001000359/0001012870-01-000359.txt: cannot access local variable 'result' where it is not associated with a value
[2025-06-06 18:36:38] [*] No background section found for index 0: Prime Response Inc & Chordiant Software Inc. Retrying via fallback...
[2025-06-06 18:36:38] [-] Confirmed no background section found for index 0: Prime Response Inc & Chordiant Software Inc.
	Dumping its document links:
		https://www.sec.gov/Archives/edgar/data/1042134/000101287001000987/0001012870-01-000987.txt
		https://www.sec.gov/Archives/edgar/data/1042134/000101287001000359/0001012870-01-000359.txt
[2025-06-06 18:37:30] [-] Error processing https://www.sec.gov/Archives/edgar/data/1042134/000101287001000359/0001012870-01-000359.txt: cannot access local variable 'result' where it is not associated with a value
[2025-06-06 18:37:34] [-] Error processing https://www.sec.gov/Archives/edgar/data/1042134/000101287001000987/0001012870-01-000987.txt: cannot access local variable 'result' where it is not associated with a value
[2025-06-06 18:37:34] [*] No background section found for index 0: Prime Response Inc & Chordiant Software Inc. Retrying via fallback...
[2025-06-06 18:37:34] [-] Confirmed no background section found for index 0: Prime Response Inc & Chordiant Software Inc.
	Dumping its document links:
		https://www.sec.gov/Archives/edgar/data/1042134/000101287001000987/0001012870-01-000987.txt
		https://www.sec.gov/Archives/edgar/data/1042134/000101287001000359/0001012870-01-000359.txt
[2025-06-06 18:38:51] [-] Error processing https://www.sec.gov/Archives/edgar/data/1042134/000101287001000359/0001012870-01-000359.txt: cannot access local variable 'result' where it is not associated with a value
[2025-06-06 18:38:55] [-] Error processing https://www.sec.gov/Archives/edgar/data/1042134/000101287001000987/0001012870-01-000987.txt: cannot access local variable 'result' where it is not associated with a value
[2025-06-06 18:38:55] [*] No background section found for index 0: Prime Response Inc & Chordiant Software Inc. Retrying via fallback...
[2025-06-06 18:38:55] [-] Confirmed no background section found for index 0: Prime Response Inc & Chordiant Software Inc.
	Dumping its document links:
		https://www.sec.gov/Archives/edgar/data/1042134/000101287001000359/0001012870-01-000359.txt
		https://www.sec.gov/Archives/edgar/data/1042134/000101287001000987/0001012870-01-000987.txt
[2025-06-06 18:41:33] [-] Error processing https://www.sec.gov/Archives/edgar/data/1042134/000101287001000359/0001012870-01-000359.txt: cannot access local variable 'result' where it is not associated with a value
[2025-06-06 18:41:37] [-] Error processing https://www.sec.gov/Archives/edgar/data/1042134/000101287001000987/0001012870-01-000987.txt: cannot access local variable 'result' where it is not associated with a value
[2025-06-06 18:41:37] [*] No background section found for index 0: Prime Response Inc & Chordiant Software Inc. Retrying via fallback...
[2025-06-06 18:41:37] [-] Confirmed no background section found for index 0: Prime Response Inc & Chordiant Software Inc.
	Dumping its document links:
		https://www.sec.gov/Archives/edgar/data/1042134/000101287001000987/0001012870-01-000987.txt
		https://www.sec.gov/Archives/edgar/data/1042134/000101287001000359/0001012870-01-000359.txt
[2025-06-06 18:43:26] [+] Successfully created document for: Prime Response Inc & Chordiant Software Inc
[2025-06-06 18:49:16] [+] Successfully created document for: Focal Inc & Genzyme Corp
[2025-06-06 18:49:17] [+] Successfully created document for: MedPlus Inc & Quest Diagnostics Inc
[2025-06-06 18:49:21] [+] Successfully created document for: Mainspring Inc & IBM
[2025-06-06 18:49:33] [+] Successfully created document for: Learn2.com Inc & E-Stamp Corp
[2025-06-06 18:49:35] [+] Successfully created document for: Aronex Pharmaceuticals Inc & Antigenics Inc
[2025-06-06 20:01:29] [-] Process failed with error: concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\bryan\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\process.py", line 264, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: SeperatorHandler.process_single_doc() missing 1 required positional argument: 'rate_limiter_resources'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Documents\Scripts\MergeExtractor\src\seperator\SeperatorHandler.py", line 154, in runSeperator
    future.result();
    ^^^^^^^^^^^^^^^
  File "C:\Users\bryan\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bryan\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
TypeError: SeperatorHandler.process_single_doc() missing 1 required positional argument: 'rate_limiter_resources'

[2025-06-06 20:01:29] [-] Process failed with error: concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\bryan\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\process.py", line 264, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: SeperatorHandler.process_single_doc() missing 1 required positional argument: 'rate_limiter_resources'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Documents\Scripts\MergeExtractor\src\seperator\SeperatorHandler.py", line 154, in runSeperator
    future.result();
    ^^^^^^^^^^^^^^^
  File "C:\Users\bryan\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bryan\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
TypeError: SeperatorHandler.process_single_doc() missing 1 required positional argument: 'rate_limiter_resources'

[2025-06-06 20:01:29] [-] Process failed with error: concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\bryan\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\process.py", line 264, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: SeperatorHandler.process_single_doc() missing 1 required positional argument: 'rate_limiter_resources'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Documents\Scripts\MergeExtractor\src\seperator\SeperatorHandler.py", line 154, in runSeperator
    future.result();
    ^^^^^^^^^^^^^^^
  File "C:\Users\bryan\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bryan\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
TypeError: SeperatorHandler.process_single_doc() missing 1 required positional argument: 'rate_limiter_resources'

[2025-06-06 20:01:38] [-] Process failed with error: concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\bryan\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\process.py", line 264, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: SeperatorHandler.process_single_doc() missing 1 required positional argument: 'rate_limiter_resources'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Documents\Scripts\MergeExtractor\src\seperator\SeperatorHandler.py", line 154, in runSeperator
    future.result();
    ^^^^^^^^^^^^^^^
  File "C:\Users\bryan\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bryan\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
TypeError: SeperatorHandler.process_single_doc() missing 1 required positional argument: 'rate_limiter_resources'

[2025-06-06 20:01:38] [-] Process failed with error: concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\bryan\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\process.py", line 264, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: SeperatorHandler.process_single_doc() missing 1 required positional argument: 'rate_limiter_resources'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Documents\Scripts\MergeExtractor\src\seperator\SeperatorHandler.py", line 154, in runSeperator
    future.result();
    ^^^^^^^^^^^^^^^
  File "C:\Users\bryan\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bryan\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
TypeError: SeperatorHandler.process_single_doc() missing 1 required positional argument: 'rate_limiter_resources'

[2025-06-06 20:01:38] [-] Process failed with error: concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\bryan\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\process.py", line 264, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: SeperatorHandler.process_single_doc() missing 1 required positional argument: 'rate_limiter_resources'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Documents\Scripts\MergeExtractor\src\seperator\SeperatorHandler.py", line 154, in runSeperator
    future.result();
    ^^^^^^^^^^^^^^^
  File "C:\Users\bryan\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bryan\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
TypeError: SeperatorHandler.process_single_doc() missing 1 required positional argument: 'rate_limiter_resources'

[2025-06-06 20:02:13] [-] Error: name 'rate_limiter_resources' is not defined
Traceback (most recent call last):
  File "D:\Documents\Scripts\MergeExtractor\src\seperator\SeperatorHandler.py", line 72, in process_single_doc
    section_passage = chunk_processor.getSectionPassage(chunks, approx_chunks, company_names, executor, rate_limiter_resources);
                                                                                                        ^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'rate_limiter_resources' is not defined

[2025-06-06 20:02:14] [-] Error: name 'rate_limiter_resources' is not defined
Traceback (most recent call last):
  File "D:\Documents\Scripts\MergeExtractor\src\seperator\SeperatorHandler.py", line 72, in process_single_doc
    section_passage = chunk_processor.getSectionPassage(chunks, approx_chunks, company_names, executor, rate_limiter_resources);
                                                                                                        ^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'rate_limiter_resources' is not defined

